# Fix colors
set-option -sa terminal-overrides ",xterm*:Tc"

# Add Mouse support
set -g mouse on

# Shift ALT vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Set a C-Space as new prefix
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# Key bind for disabling the status bar
bind s set status

# Set the base index for windows and panes to 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

# Don't ask for confirmation to kill a pane
bind-key x kill-pane

# Make panes and windows splits to use current working directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Set theme flavor
set -g @catppuccin_flavour 'mocha'

# Install plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin  'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
