#################
### AUTOSTART ###
#################
exec-once = hyprctl dispatch workspace 1
exec-once = nm-applet &
exec-once = $bar & $paper & $browser
exec-once = swayidle -w timeout 3600 'hyprlock' before-sleep 'hyprlock'
exec-once = $nextWallpaper
exec-once = $terminal
