general {
	disable_loading_bar = true
	no_fade_in = false
	blur = true
}
input-field {
	monitor = eDP-1
	size = 300, 60
	position = 0, 0
	valign = center
	halign = center
	placeholder_text = Password...
	dots_center = true
	font_color = rgba(ffffffaa)
	outer_color = rgba(ffffffaa)
	inner_color = rgba(333333cc)
	rounding = 16
	border_size = 3
	fade_on_empty = false
}
background {
	monitor = eDP-1
	path = /tmp/hyprlock/eDP-1.png
}

label {
	monitor = eDP-1
	text = cmd[update:1] date +"%H:%M"
	position = -50, 0
	halign = right
	valign = top
	font_size = 64
	color = rgba(ffffffaa)
}
label {
	monitor = eDP-1
	text = cmd[update:1] date +"%A, %d %B"
	position = -50, -100
	halign = right
	valign = top
	font_size = 36
	color = rgba(ffffffaa)
}
