# exec-once = ~/.config/hypr/scripts/gen-host-config.sh
source = ~/.config/hypr/conf/host-specific.conf
source = ~/.config/hypr/conf/shared/variables.conf
source = ~/.config/hypr/conf/shared/autostart.conf
source = ~/.config/hypr/conf/shared/env.conf
source = ~/.config/hypr/conf/shared/look-and-feel.conf
source = ~/.config/hypr/conf/shared/input.conf
source = ~/.config/hypr/conf/shared/keybindings.conf
source = ~/.config/hypr/conf/shared/windowrule.conf
