#################
### AUTOSTART ###
#################
exec-once = ~/.config/hypr/scripts/start-keyring.sh
exec-once = hyprctl dispatch workspace 1
exec-once = nm-applet &
exec-once = (sleep 1 && $bar) & $paper
# exec-once = $browser
exec-once = swayidle -w timeout 3600 'hyprlock' before-sleep 'hyprlock'
exec-once = $nextWallpaper
exec-once = $terminal
