###################
### MY PROGRAMS ###
###################
$browser = brave
$terminal = wezterm
$fileManager = thunar
$menu = wofi --show drun
$bar = waybar
$paper = hyprpaper
$screenshot = ~/.config/hypr/scripts/screenshot.sh
$teamviewer = ~/.config/hypr/scripts/teamviewer-x11.sh
$nextWallpaper = ~/.cargo/bin/wallpaper-switcher
$sshMenu = ~/.config/hypr/scripts/ssh-menu.sh
