###################
### MY PROGRAMS ###
###################
$inputSelect = /home/shane/.local/bin/input-select.sh
$browser = librewolf
$terminal = wezterm
$fileManager = thunar
$menu = wofi --show drun
$bar = waybar
$paper = hyprpaper
$screenshot = screenshot.sh
$teamviewer = teamviewer-x11.sh
$nextWallpaper = wallpaper-switcher
$sshMenu = ssh-menu.sh
